name: gnome-nibbles
adopt-info: gnome-nibbles
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

layout:
  /usr/share/gnome-nibbles:
    bind: $SNAP/usr/share/gnome-nibbles

slots:
  # for GtkApplication registration
  gnome-nibbles:
    interface: dbus
    bus: session
    name: org.gnome.Nibbles

apps:
  gnome-nibbles:
    extensions: [gnome-3-38]
    command: usr/bin/gnome-nibbles
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.Nibbles.desktop
    common-id: org.gnome.Nibbles.desktop

parts:
  gnome-nibbles:
    source: https://gitlab.gnome.org/GNOME/gnome-nibbles.git
    source-type: git
    source-tag: 3.38.2
    plugin: meson
    meson-parameters: [--prefix=/usr]
    parse-info: [usr/share/metainfo/org.gnome.Nibbles.appdata.xml]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Nibbles$|=${SNAP}/meta/gui/org.gnome.Nibbles.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Nibbles.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Nibbles.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/gnome-nibbles/current/usr: usr
