name: gnome-nibbles
adopt-info: gnome-nibbles
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

layout:
  /usr/share/gnome-nibbles:
    bind: $SNAP/usr/share/gnome-nibbles

slots:
  # for GtkApplication registration
  gnome-nibbles:
    interface: dbus
    bus: session
    name: org.gnome.Nibbles

apps:
  gnome-nibbles:
    extensions: [gnome-3-28]
    command: usr/bin/gnome-nibbles
    plugs:
      - gsettings
      - opengl
      - pulseaudio
    desktop: usr/share/applications/org.gnome.Nibbles.desktop
    common-id: org.gnome.Nibbles.desktop

parts:
  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/gnome-nibbles/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/gnome-nibbles/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - gtk-doc-tools

  gsound:
    after: [libcanberra]
    source: https://gitlab.gnome.org/GNOME/gsound.git
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gnome-nibbles/current/usr, --disable-Werror]
    organize:
      snap/gnome-nibbles/current/usr: usr
    build-packages:
      - autoconf-archive
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - valac

  gnome-nibbles:
    after: [libcanberra, gsound]
    source: https://gitlab.gnome.org/GNOME/gnome-nibbles.git
    source-type: git
    source-tag: 3.34.0
    plugin: meson
    meson-parameters: [--prefix=/usr]
    parse-info: [usr/share/metainfo/org.gnome.Nibbles.appdata.xml]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      cp $SNAPCRAFT_STAGE/usr/share/vala/vapi/gsound.vapi src/vapi/
      sed -i.bak -e 's|=org.gnome.Nibbles$|=${SNAP}/meta/gui/org.gnome.Nibbles.svg|g' data/org.gnome.Nibbles.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Nibbles.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      # Hack to work around summary not properly tagged
      sed -i.bak -e 's|_summary|summary|g' $SNAPCRAFT_PART_INSTALL/usr/share/metainfo/org.gnome.Nibbles.appdata.xml
    organize:
      snap/gnome-nibbles/current/usr: usr
    build-packages:
      - gettext
      - gnome-common
      - intltool
      - appstream-util
      - libcanberra-gtk3-dev
      - libclutter-1.0-dev
      - libclutter-gtk-1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - yelp-tools
      - libgnome-games-support-1-dev
      - libgee-0.8-dev
      - valac
  libraries:
    plugin: nil
    stage-packages:
      - libclutter-gtk-1.0-0
      - libgnome-games-support-1-3
      - libgee-0.8-2
    prime:
      - "usr/lib/*/libgnome-games-support-1.so.*"
      - "usr/lib/*/libgee-0.8.so.*"
